# Generated by Django 2.1.5 on 2022-03-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artyParty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='user_id',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='user_id',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='userID',
        ),
    ]
