# Generated by Django 2.1.5 on 2022-03-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyParty', '0002_auto_20220320_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='userID',
            field=models.IntegerField(),
        ),
    ]
