# Generated by Django 2.1.5 on 2022-03-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artyParty', '0004_auto_20220321_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
    ]
