# Generated by Django 2.1.5 on 2022-03-21 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artyParty', '0005_auto_20220321_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
